global using ApiMayUnitTest24.Modules;
global using Newtonsoft.Json;
global using NUnit.Framework;
global using RestSharp;
global using SpecFlowProjectApiMay24.ApiActions;
global using SpecFlowProjectApiMay24.Modules;
global using TechTalk.SpecFlow;
global using TechTalk.SpecFlow.Assist;
global using System.Net;
